services:
  - type: web
    name: fb-page-create
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SELENIUM_HEADLESS
        value: "True"
      - key: DEBUG
        value: "False"
